# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    loaders:
        image_loader:
            flysystem:
                filesystem_service: oneup_flysystem.images_filesystem
        user_loader:
            flysystem:
                filesystem_service: oneup_flysystem.user_filesystem
        group_loader:
            flysystem:
                filesystem_service: oneup_flysystem.group_filesystem

    resolvers:
        aws_s3_resolver:
            aws_s3:
                bucket: '%env(AWS_BUCKET_NAME)%'
                client_config:
                    credentials:
                        key: '%env(AWS_ACCESS_KEY)%'
                        secret: '%env(AWS_ACCESS_SECRET)%'
                    region: '%env(AWS_REGION)%'
                    version: '%env(AWS_VERSION)%'
                acl: private
                cache_prefix: cache

                get_options:
                    Scheme: 'https'
                put_options:
                    CacheControl: 'max-age=86400'

    filter_sets:
        cache: ~
        image_thumbnail:
            cache: aws_s3_resolver
            quality: 100
            filters:
                thumbnail: { size: [ 250, 250 ], mode: outbound }
            data_loader: image_loader
        user_thumbnail:
            cache: aws_s3_resolver
            quality: 100
            filters:
                thumbnail: { size: [ 150, 150 ], mode: outbound }
            data_loader: user_loader
        group_thumbnail:
            cache: aws_s3_resolver
            quality: 100
            filters:
                thumbnail: { size: [ 720, 360 ], mode: outbound }
            data_loader: group_loader
