name: onecam
type: php
docroot: public
php_version: "8.2"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: postgres
    version: "16"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
ngrok_args: --domain=lamb-uncommon-goose.ngrok-free.app
